### ISSUE TITLE
GUI wallet has been installed via snap, but there is no blurd

### ISSUE THREAD

**Issue by Shekelme** [blur-network/blur-network-gui#3]
After a long being off the BLUR I've made a fresh BLUR GUI wallet installation via snap on one of my Ubuntu 20.04 PCs. The wallet itself can start normally and it's able to communicate with remote node, but it can't start the local daemon. Neither can I find the blurd location to try to start it manually.

**Comment by who-biz** [comment]
This has been fixed, following your bug report on Discord. 

Thanks again for reporting!

**Comment by Shekelme** [comment]
![image](https://user-images.githubusercontent.com/26449500/88253480-50482c00-ccdc-11ea-9418-7ff55bd1959f.png)

**Comment by who-biz** [comment]
Just posting here that we spoke again on discord, and issue is resolved, for onlookers.
